/**
 * Pay Per Crawl Worker
 *
 * Blocks AI crawlers with HTTP 402 Payment Required unless they pay.
 * Uses x402 v2.0.0 protocol format.
 *
 * PREREQUISITES:
 *   1. Enterprise Bot Management enabled on your zone
 *   2. Pay Per Crawl Beta enabled for your account
 *
 * CONFIG:
 *   Pricing rules are loaded from config.json (generated by build script).
 *   Edit wrangler.jsonc and run `npm run build:config` to regenerate.
 *
 * @see AGENTS.md for setup instructions
 * @see https://developers.cloudflare.com/ai-crawl-control/features/pay-per-crawl/
 */

// Import config - Wrangler bundles this as a separate module that dashboard can parse
import configData from "./config.json";

import { validateConfig, evaluateRules, evaluateCondition } from "./rules";
import { createPaymentRequiredResponse, formatCrawlerPrice } from "./x402";
import { WARN_NO_BOT_MANAGEMENT, WARN_NO_IN_BAND_PRICING } from "./constants";
import type { Env, CfProperties, PayPerCrawlConfig } from "./types";

// =============================================================================
// Bot Detection ID Reference (for maintainability)
// =============================================================================
// These IDs are resolved from bot names during build. See src/bots.ts for full list.
//
// Search Engine Crawlers:
//   120623194 = Googlebot
//   117479730 = BingBot
//   120424214 = Applebot
//
// AI Crawlers:
//   123815556 = GPTBot (OpenAI)
//   133621792 = CCBot (Common Crawl)
//   133730073 = Google-CloudVertexBot
//   124581738 = Meta-ExternalAgent
//   118601807 = Amazonbot
//
// AI Assistants:
//   132995013 = ChatGPT-User
//   129220581 = ChatGPT agent
//   128950951 = MistralAI-User
//   126666910 = DuckAssistBot
//   132272919 = Meta-ExternalFetcher
//
// AI Search:
//   126255384 = OAI-SearchBot
//
// Archivers:
//   131190766 = archive.org_bot
//
// =============================================================================

// Cast config to PayPerCrawlConfig (TypeScript infers generic JSON type)
const config = configData as unknown as PayPerCrawlConfig;

export default {
	async fetch(request: Request, env: Env): Promise<Response> {
		const url = new URL(request.url);
		const path = url.pathname;

		// Validate config structure (logs warnings for any issues)
		validateConfig(config);

		// Get bot management data from cf object
		const cf = request.cf as CfProperties | undefined;
		const botManagement = cf?.botManagement;

		// =====================================================================
		// SHORT-CIRCUIT: No Bot Management → pass through to origin
		// =====================================================================
		if (!botManagement) {
			console.warn(WARN_NO_BOT_MANAGEMENT);
			return fetch(request);
		}

		// Extract bot data
		const botScore = botManagement.score ?? 99;
		const isVerifiedBot = botManagement.verifiedBot ?? false;
		const detectionIds = (botManagement.detectionIds ?? []).map(String);

		// Check for in-band pricing header
		const cfPayPerCrawl = request.headers.get("cf-pay-per-crawl") || "";
		const inBandPricingEnabled = cfPayPerCrawl.includes("pricing=in-band");

		if (!inBandPricingEnabled) {
			console.warn(WARN_NO_IN_BAND_PRICING);
			// Continue with pricing logic (don't short-circuit)
		}

		// =====================================================================
		// Evaluate pricing rules
		// =====================================================================
		const result = evaluateRules(path, botScore, isVerifiedBot, detectionIds, config);

		if (result.shouldBlock && result.price !== null) {
			// Rule matched, no exception → return 402
			return createPaymentRequiredResponse(path, result.price);
		}

		// =====================================================================
		// No rule matched or exception applied → proxy to origin
		// =====================================================================
		const response = await fetch(request);

		// Add Crawler-Price header if in-band pricing is enabled
		if (inBandPricingEnabled) {
			const newResponse = new Response(response.body, response);

			// Find applicable price for this path
			let priceSet = false;
			for (const rule of config.config.rules) {
				if (rule.enabled && evaluateCondition(rule.condition, { requestPath: path, botScore, detectionIds })) {
					newResponse.headers.set("Crawler-Price", formatCrawlerPrice(rule.action.chargeAmount ?? 0));
					priceSet = true;
					break;
				}
			}

			// No matching rule → price is $0.00
			if (!priceSet) {
				newResponse.headers.set("Crawler-Price", "USD 0.00");
			}

			return newResponse;
		}

		return response;
	},
};
