/**
 * Pay Per Crawl - Rule Evaluation
 *
 * Evaluates stratus-compatible PayPerCrawlRule structures.
 * Config is loaded from config.json (generated by build script).
 */

import type {
	PayPerCrawlRule,
	PayPerCrawlConfig,
	RuleCondition,
	RuleException,
} from "./types";

// =============================================================================
// Condition Evaluation
// =============================================================================

const OPERATOR_FNS: Record<string, (a: unknown, b: unknown) => boolean> = {
	eq: (a, b) => a === b,
	ne: (a, b) => a !== b,
	ge: (a, b) => typeof a === "number" && typeof b === "number" && a >= b,
	gt: (a, b) => typeof a === "number" && typeof b === "number" && a > b,
	le: (a, b) => typeof a === "number" && typeof b === "number" && a <= b,
	lt: (a, b) => typeof a === "number" && typeof b === "number" && a < b,
	starts_with: (a, b) =>
		typeof a === "string" && typeof b === "string" && a.startsWith(b),
	ends_with: (a, b) =>
		typeof a === "string" && typeof b === "string" && a.endsWith(b),
	contains: (a, b) =>
		typeof a === "string" && typeof b === "string" && a.includes(b),
};

/**
 * Context for evaluating conditions.
 */
export interface EvaluationContext {
	requestPath: string;
	contentType?: string;
	botScore: number;
	detectionIds: string[];
}

/**
 * Evaluate a condition against the context.
 */
export function evaluateCondition(
	condition: RuleCondition,
	context: EvaluationContext
): boolean {
	const { field, operator, value } = condition;

	// Get field value from context
	const fieldValue = context[field as keyof EvaluationContext];

	// Apply operator
	const operatorFn = OPERATOR_FNS[operator];
	if (!operatorFn) {
		console.warn(`[pay-per-crawl] Unknown operator: ${operator}`);
		return false;
	}

	return operatorFn(fieldValue, value);
}

// =============================================================================
// Exception Evaluation
// =============================================================================

/**
 * Check if any exception allows this request through.
 * Returns true if request should be BLOCKED (no exception matched).
 * Returns false if request should be ALLOWED (an exception matched).
 */
export function shouldBlock(
	exceptions: RuleException[] | undefined,
	context: EvaluationContext
): boolean {
	if (!exceptions || exceptions.length === 0) {
		// No exceptions defined - block
		return true;
	}

	for (const exception of exceptions) {
		// Bot score exception
		if (exception.type === "botScore") {
			const { botScoreOperator, botScoreValue } = exception;
			if (botScoreOperator && botScoreValue !== undefined) {
				const operatorFn = OPERATOR_FNS[botScoreOperator];
				if (operatorFn && operatorFn(context.botScore, botScoreValue)) {
					// Bot score meets exception threshold - ALLOW
					return false;
				}
			}
		}

		// Bot ID exception
		if (exception.type === "bots" && exception.bots && exception.bots.length > 0) {
			// Check if any of the request's detection IDs match the exception list
			const hasMatchingBot = exception.bots.some((id) =>
				context.detectionIds.includes(String(id))
			);
			if (hasMatchingBot) {
				// Bot is in exception list - ALLOW
				return false;
			}
		}
	}

	// No exception matched - BLOCK
	return true;
}

// =============================================================================
// Rule Evaluation
// =============================================================================

/**
 * Result of rule evaluation.
 */
export interface EvaluationResult {
	/** The rule that matched, or null if no rule matched */
	rule: PayPerCrawlRule | null;
	/** The price to charge (from rule.action.chargeAmount) */
	price: number | null;
	/** Whether the request should be blocked */
	shouldBlock: boolean;
}

/**
 * Evaluate pricing rules against a request.
 *
 * Returns:
 * - rule: The first matching rule, or null if no rule matched
 * - price: The charge amount from the matching rule
 * - shouldBlock: Whether to return 402 (true) or allow through (false)
 *
 * A request is ALLOWED (shouldBlock = false) if:
 * - Path doesn't match any rule's condition
 * - Rule is disabled
 * - Request is from a verified bot
 * - An exception matches (bot score >= threshold, or bot in exception list)
 *
 * A request is BLOCKED (shouldBlock = true) if:
 * - Path matches a rule's condition AND
 * - Rule is enabled AND
 * - Not a verified bot AND
 * - No exception matches
 */
export function evaluateRules(
	path: string,
	botScore: number,
	isVerifiedBot: boolean,
	detectionIds: string[],
	config: PayPerCrawlConfig
): EvaluationResult {
	const context: EvaluationContext = {
		requestPath: path,
		botScore,
		detectionIds,
	};

	const rules = config.config.rules;

	for (const rule of rules) {
		// Skip disabled rules
		if (!rule.enabled) {
			continue;
		}

		// Check if condition matches
		if (!evaluateCondition(rule.condition, context)) {
			continue;
		}

		// Verified bots always pass (matches WAF behavior)
		if (isVerifiedBot) {
			return {
				rule,
				price: rule.action.chargeAmount ?? null,
				shouldBlock: false,
			};
		}

		// Check exceptions
		if (!shouldBlock(rule.exceptions, context)) {
			// An exception matched - allow through
			return {
				rule,
				price: rule.action.chargeAmount ?? null,
				shouldBlock: false,
			};
		}

		// No exception matched - block with this rule
		return {
			rule,
			price: rule.action.chargeAmount ?? null,
			shouldBlock: true,
		};
	}

	// No rule matched
	return {
		rule: null,
		price: null,
		shouldBlock: false,
	};
}

/**
 * Validate config structure at startup.
 * Logs warnings for any issues.
 */
export function validateConfig(config: PayPerCrawlConfig): void {
	if (!config || !config.config || !Array.isArray(config.config.rules)) {
		console.error("[pay-per-crawl] Invalid config structure. Expected { config: { rules: [] } }");
		return;
	}

	const rules = config.config.rules;

	if (rules.length === 0) {
		console.warn("[pay-per-crawl] No rules configured. All traffic will pass through.");
		return;
	}

	console.log(`[pay-per-crawl] Loaded ${rules.length} pricing rule(s)`);

	for (let i = 0; i < rules.length; i++) {
		const rule = rules[i];

		// Basic structure validation
		if (!rule.id) {
			console.warn(`[pay-per-crawl] Rule ${i + 1}: Missing 'id' field`);
		}

		if (!rule.condition || !rule.condition.field || !rule.condition.operator) {
			console.error(`[pay-per-crawl] Rule ${i + 1}: Invalid condition structure`);
		}

		if (!rule.action || typeof rule.action.chargeAmount !== "number") {
			console.warn(`[pay-per-crawl] Rule ${i + 1}: Missing or invalid chargeAmount`);
		}

		if (typeof rule.enabled !== "boolean") {
			console.warn(`[pay-per-crawl] Rule ${i + 1}: Missing 'enabled' field, treating as enabled`);
		}
	}
}
